apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-update-api-version

resources:
- ../initial

patches:
- patch: |
    - op: replace
      path: /apiVersion
      value: test.example.com/v2
  target:
    group: test.example.com
    version: v1
    kind: Versionupdate
    name: vuco
    namespace: test-update-api-version
